// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5BzDfXWaBmpWfAc7-hGFtxcXJzfPgC6k',
    appId: '1:502772036256:web:bcbac15a9a0a2a0839cfc5',
    messagingSenderId: '502772036256',
    projectId: 'segyoschoolapp',
    authDomain: 'segyoschoolapp.firebaseapp.com',
    storageBucket: 'segyoschoolapp.firebasestorage.app',
    measurementId: 'G-MS9CPG30M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yrkc9FKzce8EMHqgrydLUq0rXXwbC9E',
    appId: '1:502772036256:android:888efde4704b695839cfc5',
    messagingSenderId: '502772036256',
    projectId: 'segyoschoolapp',
    storageBucket: 'segyoschoolapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpFZHvFPbxufqivQkIRNJnfTxeYPuQtrA',
    appId: '1:502772036256:ios:eabf5245acb8814739cfc5',
    messagingSenderId: '502772036256',
    projectId: 'segyoschoolapp',
    storageBucket: 'segyoschoolapp.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpFZHvFPbxufqivQkIRNJnfTxeYPuQtrA',
    appId: '1:502772036256:ios:eabf5245acb8814739cfc5',
    messagingSenderId: '502772036256',
    projectId: 'segyoschoolapp',
    storageBucket: 'segyoschoolapp.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5BzDfXWaBmpWfAc7-hGFtxcXJzfPgC6k',
    appId: '1:502772036256:web:0691f343434672d539cfc5',
    messagingSenderId: '502772036256',
    projectId: 'segyoschoolapp',
    authDomain: 'segyoschoolapp.firebaseapp.com',
    storageBucket: 'segyoschoolapp.firebasestorage.app',
    measurementId: 'G-GP40Z51SW5',
  );
}
